name: build_and_test

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything to determine version from git.
          fetch-depth: 0
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Update pip/wheel infrastructure
        run: |
          pip install --upgrade "setuptools<60" pip wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        run: |
          pip install \
            flake8 \
            pytest pytest-flake8 pytest-xdist pytest-openfiles pytest-cov

      - name: List installed packages
        run: |
          pip list -v

      - name: Build and install
        run: |
          pip install --no-deps -v -e .

      - name: Run tests
        run: |
          pytest -r a -v --open-files --cov=python --cov=tests --cov-report=xml --cov-report=term --cov-branch
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
